### PR TITLE
Fix for UNSAFE lifecycle warning for React 16.9.0

### PR DESCRIPTION
**Pull request by gtgalone**
Thank you, I am using this library well.

But after updating React 16.9.0, I got the warning for UNSAFE lifecycle with deprecated.

So There is a guideline to patch. https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html#gradual-migration-path

I executed that and update and change eslint rule for UNSAFE_ lifecycle.

Thank you

### CODE REVIEW

**Comment by maslianok** [comment]
@gtgalone Thanks for your PR and sorry for not answering for a long time!

React 16.9 introduces warnings for UNSAFE_ methods as well
https://github.com/facebook/react/blob/master/CHANGELOG.md#1690-august-8-2019

and they will be removed in React@17.
So I think there is no sense to merge this. Let me try to rework deprecated methods...

**Comment by gtgalone** [comment]
@maslianok That sounds good. I think so!
I am happy to get your reply. and I will wait for your commit.

**Comment by maslianok** [comment]
@gtgalone fixed in v3.3.0

Commit https://github.com/maslianok/react-responsive-tabs/commit/f733b542872934d089fdd78509959407b010c5a7#diff-1fdf421c05c1140f6d71444ea2b27638L36

**Comment by gtgalone** [comment]
Thank you awesome !

**Pull request closed without merging**
